// Generated by scripts/run-to-capture.mjs from a real saturn run (#2, 2026-10-03).
// Do not edit — re-run the script.
import type { CaptureRun } from "./types";

export const capture: CaptureRun = {
  "id": 2,
  "date": "2026-10-03",
  "model": "qwen3.8:27b",
  "saturnVersion": "0.1.0",
  "query": "how much did I spend on groceries in september? it's all in groceries.csv",
  "status": "ok",
  "rows": [
    {
      "kind": "agent",
      "iter": 1,
      "durS": 7.32,
      "contextTokens": 7392,
      "tokPerSec": 11.5,
      "calls": [
        "read_file"
      ]
    },
    {
      "kind": "tool",
      "call": "read_file(file_path='groceries.csv')",
      "result": "date,store,amount 2026-09-02,trader joe's,48.17 2026-09-06,farmers market,22.50 2026-09-11,whole…",
      "ok": true
    },
    {
      "kind": "agent",
      "iter": 2,
      "durS": 7,
      "contextTokens": 7567,
      "tokPerSec": 12.5,
      "calls": [
        "calculate"
      ]
    },
    {
      "kind": "tool",
      "call": "calculate(expression='48.17 + 22.50 + 71.36 + 39.82 + 112.40 + 18.75')",
      "result": "313",
      "ok": true
    },
    {
      "kind": "agent",
      "iter": 3,
      "durS": 10.46,
      "contextTokens": 7653,
      "tokPerSec": 11.9,
      "calls": null
    }
  ],
  "metrics": {
    "contextTokens": 7653,
    "tokPerSec": 11.9,
    "durationS": 24.8
  },
  "response": "You spent **$313.00** on groceries in September — 6 trips:\n\n- Sep 2 — Trader Joe's — $48.17\n- Sep 6 — Farmers market — $22.50\n- Sep 11 — Whole Foods — $71.36\n- Sep 15 — Trader Joe's — $39.82\n- Sep 21 — Costco — $112.40\n- Sep 27 — Farmers market — $18.75\n\nSources:\n  [1] read_file(file_path='groceries.csv')\n  [2] calculate(expression='48.17 + 22.50 + 71.36 + 39.82 + 112.40 + 18.75')"
};
