// Generated by scripts/run-to-capture.mjs from a real saturn run (#6, 2026-10-03).
// Do not edit — re-run the script.
import type { CaptureRun } from "./types";

export const capture: CaptureRun = {
  "id": 6,
  "date": "2026-10-03",
  "model": "qwen3.8:27b",
  "saturnVersion": "0.1.0",
  "query": "save a two-line summary of groceries.csv to notes.md",
  "status": "ok",
  "rows": [
    {
      "kind": "agent",
      "iter": 1,
      "durS": 7.34,
      "contextTokens": 7387,
      "tokPerSec": 11.5,
      "calls": [
        "read_file"
      ]
    },
    {
      "kind": "tool",
      "call": "read_file(file_path='groceries.csv')",
      "result": "date,store,amount 2026-09-02,trader joe's,48.17 2026-09-06,farmers market,22.50 2026-09-11,whole…",
      "ok": true
    },
    {
      "kind": "agent",
      "iter": 2,
      "durS": 7.01,
      "contextTokens": 7562,
      "tokPerSec": 12.5,
      "calls": [
        "calculate"
      ]
    },
    {
      "kind": "tool",
      "call": "calculate(expression='48.17 + 22.50 + 71.36 + 39.82 + 112.40 + 18.75')",
      "result": "313",
      "ok": true
    },
    {
      "kind": "agent",
      "iter": 3,
      "durS": 12.5,
      "contextTokens": 7648,
      "tokPerSec": 9.9,
      "calls": [
        "write_file"
      ]
    },
    {
      "kind": "gate",
      "decision": "rejected",
      "calls": [
        {
          "name": "write_file",
          "approved": false
        }
      ]
    },
    {
      "kind": "agent",
      "iter": 4,
      "durS": 13.61,
      "contextTokens": 7804,
      "tokPerSec": 9.8,
      "calls": null
    }
  ],
  "metrics": {
    "contextTokens": 7804,
    "tokPerSec": 9.8,
    "durationS": 40.5
  },
  "response": "I didn't write to notes.md — that action was declined.\n\nFor reference, the two-line summary I was about to save:\n\n> Groceries (Sept 2026): 6 trips totaling $313.00, from $18.75 (farmers market) to $112.40 (Costco).\n> Most frequent stores: Trader Joe's (2 trips) and farmers market (2 trips); biggest single spend was Costco at $112.40.\n\nWant me to adjust the wording, or save it somewhere else?\n\nNote — the following could not be completed:\n- write_file(file_path='notes.md', content=\"Groceries (Sept 2026): 6 trips totaling $313.00, from $18.…) — declined at the approval gate — not done\n\nSources:\n  [1] read_file(file_path='groceries.csv')\n  [2] calculate(expression='48.17 + 22.50 + 71.36 + 39.82 + 112.40 + 18.75')"
};
