// Generated by scripts/run-to-capture.mjs from a real saturn run (#155, 2026-08-14).
// Do not edit — re-run the script.
import type { CaptureRun } from "./types";

export const capture: CaptureRun = {
  "id": 155,
  "date": "2026-08-14",
  "model": "qwen3.6:27b",
  "saturnVersion": "0.1.0",
  "query": "create a file named hello.txt containing the word hi",
  "status": "ok",
  "nodes": [
    {
      "node": "plan",
      "model": "qwen3.6:27b",
      "durS": 2.49,
      "promptTokens": 4504,
      "outputTokens": 25
    },
    {
      "node": "execute",
      "model": "qwen3.6:27b",
      "durS": 1.96,
      "promptTokens": 1889,
      "outputTokens": 83
    },
    {
      "node": "synthesize",
      "model": "qwen3.6:27b",
      "durS": 7.52,
      "promptTokens": 1639,
      "outputTokens": 485
    }
  ],
  "plan": [
    {
      "label": "Create hello.txt containing the word hi",
      "status": "skipped",
      "intendedTool": "write_file"
    }
  ],
  "gates": [
    {
      "step": "Create hello.txt containing the word hi",
      "decision": "rejected",
      "calls": [
        {
          "name": "write_file",
          "approved": false
        }
      ]
    }
  ],
  "metrics": {
    "contextTokens": 1639,
    "tokPerSec": 70.6,
    "durationS": 12.37
  },
  "answer": [
    {
      "text": "I did not",
      "level": 0
    },
    {
      "text": " create `",
      "level": 2
    },
    {
      "text": "hello.txt` because the",
      "level": 0
    },
    {
      "text": " file",
      "level": 1
    },
    {
      "text": "-writing",
      "level": 3
    },
    {
      "text": " action was declined during execution.",
      "level": 0
    },
    {
      "text": " Consequently",
      "level": 4
    },
    {
      "text": ", the file was",
      "level": 0
    },
    {
      "text": " never",
      "level": 3
    },
    {
      "text": " written",
      "level": 1
    },
    {
      "text": " to",
      "level": 0
    },
    {
      "text": " the",
      "level": 1
    },
    {
      "text": " workspace.",
      "level": 0
    },
    {
      "text": " Let",
      "level": 1
    },
    {
      "text": " me know if",
      "level": 0
    },
    {
      "text": " there",
      "level": 2
    },
    {
      "text": " is",
      "level": 3
    },
    {
      "text": " anything else",
      "level": 0
    },
    {
      "text": " I",
      "level": 1
    },
    {
      "text": " can",
      "level": 0
    },
    {
      "text": " help you",
      "level": 1
    },
    {
      "text": " with",
      "level": 0
    },
    {
      "text": "!",
      "level": 1
    }
  ],
  "response": "I did not create `hello.txt` because the file-writing action was declined during execution. Consequently, the file was never written to the workspace. Let me know if there is anything else I can help you with!\n\nNote — the following could not be completed:\n- step 1 (Create hello.txt containing the word hi): Execution declined by the user. Do not retry this action; tell the user you did not perform it."
};
