import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"
import "./globals.css";
import Footer from "./components/footer";
import Navbar from "./components/navbar";



export const metadata: Metadata = {
  title: "Saturday.ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://api.fontshare.com" rel="stylesheet"></link>
      </head>
      <body className="antialiased w-full bg-zinc-50">

        <Navbar/>

        {children}
        
        <Analytics/>
        <SpeedInsights/>

        <Footer/>
      </body>
    </html>
  );
}
